package com.ahadu.arithmetics;

/**
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
 * The first ten terms would be:
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * Let us list the factors of the first seven triangle numbers:
 * 
 * 
 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.
What is the value of the first triangle number to have over five hundred divisors?
 * @author at
 */
public class HighlyDivisibleTriangularNumber {

	public static void main( String[] args){
		System.out.println(getFirstTriangleNumWithNDivisors(500));
	}

	private static int getFirstTriangleNumWithNDivisors(int n){
		int triangular = 0;
		int count = 1;
		while(true){	
			triangular = getNthTriangularNumber(count++);
			if(getNumberOfDivisors(triangular)>=n){
				return triangular;
			}
		}
	}
	
	private static int getNumberOfDivisors(int triangular) {
		int divs = 0;
		for (int i = triangular; i >= 1 ; i--) {
			if(triangular % i == 0){
				divs++;
			}
		}
		return divs;
	}

	private static int getNthTriangularNumber(int i) {
		int triangular = 0;
		for (int j = 1; j <= i; j++) {
			triangular += j;
		}
		return triangular;
	}

	
	
}
